index:
    path: /
    controller: App\Controller\TechNews\FrontController::index

accueil:
    path: /accueil
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true

home:
    path: /homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true



mentions_legales:
    path: /mentions-legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentionslegales.html.twig


mentionslegales:
    path: /mentionslegales
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: mentions_legales
        permanent: true